import nltk

uni_words = [[('Electronics','DEP')],
                [('EC','DEP')],
                [('IT','DEP')],
                [('CS','DEP')],
                [('EEE','DEP')],
                [('Mining','DEP')],
                [('Civil','DEP')],
                [('Meta','DEP')],
                [('Metallurgy','DEP')],
                [('Electrical','DEP')],
                [('Comps','DEP')],
                [('Chemical','DEP')],
                [('Chem','DEP')],
                [('Mech','DEP')],
                [('Mechanical','DEP')],
                [('ACM','CLUB')],
                [('IEEE','CLUB')],
                [('IE','CLUB')],
                [('ISTE','CLUB')],
                [('IET','CLUB')],
                [('E-Cell','CLUB')],
                [('Ecell','CLUB')],
                [('AF','CLUB')],
                [('DDFC','CLUB')],
                [('MT1','HOS')],
                [('MT-1','HOS')],
                [('MT2','HOS')],
                [('MT-2','HOS')],
                [('MT3','HOS')],
                [('MT-3','HOS')],
                [('SJA','REC')],
                [('SAC','REC')],
                [('Beach','REC')],
                [('ATB','CLA')],
                [('NTB','CLA')],
                ]


bi_words = [[('Electronics','DEP'),('department','DEP')],
                [('EC','DEP'),('department','DEP')],
                [('IT','DEP'),('department','DEP')],
                [('CS','DEP'),('department','DEP')],
                [('EEE','DEP'),('department','DEP')],
                [('Mining','DEP'),('department','DEP')],
                [('Civil','DEP'),('department','DEP')],
                [('Meta','DEP'),('department','DEP')],
                [('Metallurgy','DEP'),('department','DEP')],
                [('Electrical','DEP'),('department','DEP')],
                [('Comps','DEP'),('department','DEP')],
                [('Chemical','DEP'),('department','DEP')],
                [('Chem','DEP'),('department','DEP')],
                [('Mechanical','DEP'),('department','DEP')],
                [('Mech','DEP'),('department','DEP')],
                [('Dance','CLUB'),('Crew','CLUB')],
                ]
